### ISSUE TITLE
Error when trying to add or edit a chain drawback.

### ISSUE THREAD

**Issue by HeyItsDeas** [thedarkwad/ChainMakerOffline#1]
On the current web and offline versions of the app whenever I try to create or edit an existing chain drawback the screen goes white and I get the following message. 

```Application Error
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at oe (http://localhost/build/_shared/chunk-TILK7L6F.js:3:3791)
    at js (http://localhost/build/_shared/chunk-TCPJRWQN.js:7:16980)
    at Wh (http://localhost/build/_shared/chunk-TCPJRWQN.js:9:43911)
    at Vh (http://localhost/build/_shared/chunk-TCPJRWQN.js:9:39686)
    at _0 (http://localhost/build/_shared/chunk-TCPJRWQN.js:9:39614)
    at Ni (http://localhost/build/_shared/chunk-TCPJRWQN.js:9:39469)
    at us (http://localhost/build/_shared/chunk-TCPJRWQN.js:9:35852)
    at Jf (http://localhost/build/_shared/chunk-TCPJRWQN.js:9:36654)
    at Mn (http://localhost/build/_shared/chunk-TCPJRWQN.js:7:3265)```

Oddly however, if I do this on the online version, once I get to the error page, if I back out I'll see a chain drawback was created, but I'm unable to edit it at all.

**Comment by thedarkwad** [comment]
Thank you for pointing this out! It's been patched in the current release.
